//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XSD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MICROSERVER1;Initial Catalog=CA_SYSTEM;User ID=sa;Password=m_pradeep2" +
            "411")]
        public string CA_SYSTEMConnectionString {
            get {
                return ((string)(this["CA_SYSTEMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MPRADEEP;Initial Catalog=CA_SYSTEM;User ID=sa;Password=m_pradeep2411")]
        public string CA_SYSTEMConnectionString1 {
            get {
                return ((string)(this["CA_SYSTEMConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MICROSERVER1;Initial Catalog=cadlive;User ID=sa;Password=m_pradeep241" +
            "1")]
        public string cadliveConnectionString {
            get {
                return ((string)(this["cadliveConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CONTADMIN;Initial Catalog=cadlive;User ID=sa;Password=Adanipmc2011$")]
        public string cadliveConnectionString1 {
            get {
                return ((string)(this["cadliveConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AARIN-PC\\sqlexpress;Initial Catalog=cad11;Integrated Security=True")]
        public string cad11ConnectionString {
            get {
                return ((string)(this["cad11ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AARIN-PC\\sqlexpress;Initial Catalog=cad21;Integrated Security=True")]
        public string cad21ConnectionString {
            get {
                return ((string)(this["cad21ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AARIN-PC\\SQLEXPRESS;Initial Catalog=cadlive;Integrated Security=True")]
        public string cadliveConnectionString2 {
            get {
                return ((string)(this["cadliveConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AARIN-PC\\SQLEXPRESS;Initial Catalog=cadlive1;Integrated Security=True" +
            "")]
        public string cadlive1ConnectionString {
            get {
                return ((string)(this["cadlive1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AARIN-PC\\sqlexpress;Initial Catalog=cadlive23;Integrated Security=Tru" +
            "e")]
        public string cadlive23ConnectionString {
            get {
                return ((string)(this["cadlive23ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AARIN-PC\\sqlexpress;Initial Catalog=cadlive30;Integrated Security=Tru" +
            "e")]
        public string cadlive30ConnectionString {
            get {
                return ((string)(this["cadlive30ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=aarin-pc\\SQLEXPRESS;Initial Catalog=cadadani;Integrated Security=True" +
            "")]
        public string cadadaniConnectionString {
            get {
                return ((string)(this["cadadaniConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=aarin-pc\\sqlexpress;Initial Catalog=adanicad;Integrated Security=True" +
            "")]
        public string adanicadConnectionString {
            get {
                return ((string)(this["adanicadConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AARIN-PC\\sqlexpress;Initial Catalog=adanicad28-2;Integrated Security=" +
            "True")]
        public string adanicad28_2ConnectionString {
            get {
                return ((string)(this["adanicad28_2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AARIN-PC\\sqlexpress;Initial Catalog=adanicadflagtemp;Integrated Secur" +
            "ity=True")]
        public string adanicadflagtempConnectionString {
            get {
                return ((string)(this["adanicadflagtempConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mitesh\\sqlexpress;Initial Catalog=adanicompliance;Integrated Security" +
            "=True")]
        public string adanicomplianceConnectionString {
            get {
                return ((string)(this["adanicomplianceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CONTADMIN;Initial Catalog=cadlive;Integrated Security=True")]
        public string cadliveConnectionString3 {
            get {
                return ((string)(this["cadliveConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mitesh\\sqlexpress;Initial Catalog=cadlive11-4-2012;Integrated Securit" +
            "y=True")]
        public string cadlive11_4_2012ConnectionString {
            get {
                return ((string)(this["cadlive11_4_2012ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KETAN-PC;Initial Catalog=cadlive05-05-2012;User ID=sa;Password=m_prad" +
            "eep2411")]
        public string cadlive05_05_2012ConnectionString {
            get {
                return ((string)(this["cadlive05_05_2012ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KETAN-PC;Initial Catalog=cadlive_25_5_2012;User ID=sa;Password=m_prad" +
            "eep2411")]
        public string cadlive_25_5_2012ConnectionString {
            get {
                return ((string)(this["cadlive_25_5_2012ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CONTADMIN;Initial Catalog=temparoary;Integrated Security=True")]
        public string temparoaryConnectionString {
            get {
                return ((string)(this["temparoaryConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=KETAN-PC\\SQLEXPRESS;Initial Catalog=cadlive;User ID=sa;Password=m_pra" +
            "deep2411")]
        public string cadliveConnectionString4 {
            get {
                return ((string)(this["cadliveConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATASERVER\\SQLEXPRESS;Initial Catalog=cadlive;Persist Security Info=T" +
            "rue;User ID=sa;Password=m_pradeep2411")]
        public string cadliveConnectionString5 {
            get {
                return ((string)(this["cadliveConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=JENISH\\SQLEXPRESS;Initial Catalog=CASDESIGN;User ID=sa;Password=m_pra" +
            "deep2411")]
        public string CASDESIGNConnectionString {
            get {
                return ((string)(this["CASDESIGNConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=mitesh;Initial Catalog=CASDESIGN;Integrated Security=True")]
        public string CASDESIGNConnectionString1 {
            get {
                return ((string)(this["CASDESIGNConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MITESH;Initial Catalog=CASDESIGN;User ID=sa;Password=m_pradeep2411")]
        public string CASDESIGNConnectionString2 {
            get {
                return ((string)(this["CASDESIGNConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=kamlesh;User Id=root;password=m_pradeep2411;database=cept")]
        public string ceptConnectionString {
            get {
                return ((string)(this["ceptConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=kamlesh;User Id=root;database=cept;password=m_pradeep2411;Persist Security" +
            " Info=True")]
        public string ceptConnectionString1 {
            get {
                return ((string)(this["ceptConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATASERVER\\SQLEXPRESS;Initial Catalog=CEPT_Reg;User ID=sa;Password=m_" +
            "pradeep2411")]
        public string CEPT_RegConnectionString {
            get {
                return ((string)(this["CEPT_RegConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WIN-GJB8GKG0WNS;Initial Catalog=CEPT_Registration;User ID=sa;Password" +
            "=cept$04@2014")]
        public string CEPT_RegistrationConnectionString {
            get {
                return ((string)(this["CEPT_RegistrationConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DATASERVER\\SQLEXPRESS;Initial Catalog=CEPT_Reg_Latest;Persist Securit" +
            "y Info=True;User ID=sa;Password=m_pradeep2411")]
        public string CEPT_Reg_LatestConnectionString {
            get {
                return ((string)(this["CEPT_Reg_LatestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FWSERVER2\\SQL2008R2;Initial Catalog=CEPT_Reg_Latest;User ID=sa;Passwo" +
            "rd=m_pradeep2411")]
        public string CEPT_Reg_LatestConnectionString1 {
            get {
                return ((string)(this["CEPT_Reg_LatestConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FWSERVER2\\SQL2008R2;Initial Catalog=CEPT_REG_LATEST1;User ID=sa;Passw" +
            "ord=m_pradeep2411")]
        public string CEPT_REG_LATEST1ConnectionString {
            get {
                return ((string)(this["CEPT_REG_LATEST1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FWSERVER2\\SQL2008R2;Initial Catalog=CEPT_Reg;User ID=sa;Password=m_pr" +
            "adeep2411")]
        public string CEPT_RegConnectionString1 {
            get {
                return ((string)(this["CEPT_RegConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FWSERVER2\\SQL2008R2;Initial Catalog=CEPT_REG_LATEST1_COPY;User ID=sa;" +
            "Password=m_pradeep2411")]
        public string CEPT_REG_LATEST1_COPYConnectionString {
            get {
                return ((string)(this["CEPT_REG_LATEST1_COPYConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FWSERVER2\\SQL2008R2;Initial Catalog=CEPT_REG_TEST;User ID=sa;Password" +
            "=m_pradeep2411")]
        public string CEPT_REG_TESTConnectionString {
            get {
                return ((string)(this["CEPT_REG_TESTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MDRA02;Initial Catalog=CEPT_REGISTRATION;Persist Security Info=True;U" +
            "ser ID=sa;Password=m_pradeep2411")]
        public string CEPT_REGISTRATIONConnectionString1 {
            get {
                return ((string)(this["CEPT_REGISTRATIONConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MDRA02;Initial Catalog=CEPT_Registration_10042019;Persist Security In" +
            "fo=True;User ID=sa;Password=m_pradeep2411")]
        public string CEPT_Registration_10042019ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_10042019ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN-PC\\MAYUR;Initial Catalog=CEPT_Registration_17052019;User ID=sa;" +
            "Password=m_pradeep2411")]
        public string CEPT_Registration_17052019ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_17052019ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN-PC\\MAYUR;Initial Catalog=CEPT_Registration_24052019;User ID=sa;" +
            "Password=m_pradeep2411")]
        public string CEPT_Registration_24052019ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_24052019ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN-PC\\MAYUR;Initial Catalog=CEPT_Registration_06062019;User ID=sa;" +
            "Password=m_pradeep2411")]
        public string CEPT_Registration_06062019ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_06062019ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN-PC\\MAYUR;Initial Catalog=CEPT_Registration;User ID=sa;Password=" +
            "m_pradeep2411")]
        public string CEPT_RegistrationConnectionString2 {
            get {
                return ((string)(this["CEPT_RegistrationConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN-PC\\MAYUR;Initial Catalog=CEPT_Registration_01072019;User ID=sa;" +
            "Password=m_pradeep2411")]
        public string CEPT_Registration_01072019ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_01072019ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN-PC\\MAYUR;Initial Catalog=CEPT_Registration;User ID=sa")]
        public string Mayur_CEPT_Registartion {
            get {
                return ((string)(this["Mayur_CEPT_Registartion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration;Integrat" +
            "ed Security=True")]
        public string CEPT_Registration_Latest_Win10 {
            get {
                return ((string)(this["CEPT_Registration_Latest_Win10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_24122019" +
            ";Integrated Security=True")]
        public string CEPT_Registration_24122019ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_24122019ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_02012020" +
            ";Integrated Security=True")]
        public string CEPT_Registration_02012020ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_02012020ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_27042020" +
            ";Integrated Security=True")]
        public string CEPT_Registration_27042020ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_27042020ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_03062020" +
            ";Integrated Security=True")]
        public string CEPT_Registration_03062020ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_03062020ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_11062020" +
            ";Integrated Security=True")]
        public string CEPT_Registration_11062020ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_11062020ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=REG20200104;Integrated Security=True")]
        public string REG20200104ConnectionString {
            get {
                return ((string)(this["REG20200104ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_26072020" +
            ";Integrated Security=True")]
        public string CEPT_Registration_26072020ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_26072020ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_11102020" +
            ";Integrated Security=True")]
        public string CEPT_Registration_11102020ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_11102020ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_27102020" +
            ";Integrated Security=True")]
        public string CEPT_Registration_27102020ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_27102020ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_27112020" +
            ";Integrated Security=True")]
        public string CEPT_Registration_27112020ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_27112020ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_14122020" +
            ";Integrated Security=True")]
        public string CEPT_Registration_14122020ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_14122020ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_04012021" +
            ";Integrated Security=True")]
        public string CEPT_Registration_04012021ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_04012021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_28012021" +
            ";Integrated Security=True")]
        public string CEPT_Registration_28012021ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_28012021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4NPATEE;Initial Catalog=BKUP_CEPT_REGISTRATION20210302;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20210302ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20210302ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_25032021" +
            ";Integrated Security=True")]
        public string CEPT_Registration_25032021ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_25032021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4NPATEE;Initial Catalog=BKUP_CEPT_REGISTRATION20210420;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20210420ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20210420ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_05072021" +
            ";Integrated Security=True")]
        public string CEPT_Registration_05072021ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_05072021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4NPATEE;Initial Catalog=BKUP_CEPT_REGISTRATION20210831;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20210831ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20210831ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4NPATEE;Initial Catalog=BKUP_CEPT_REGISTRATION20210916;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20210916ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20210916ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4NPATEE;Initial Catalog=BKUP_CEPT_REGISTRATION20210922;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20210922ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20210922ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_08102021" +
            ";Integrated Security=True")]
        public string CEPT_Registration_08102021ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_08102021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4NPATEE;Initial Catalog=BKUP_CEPT_REGISTRATION20211008;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20211008ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20211008ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4NPATEE;Initial Catalog=BKUP_CEPT_REGISTRATION20211028;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20211028ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20211028ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4NPATEE;Initial Catalog=BKUP_CEPT_REGISTRATION20211120;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20211120ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20211120ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_20112021" +
            ";Integrated Security=True")]
        public string CEPT_Registration_20112021ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_20112021ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=BKUP_CEPT_REGISTRATION20211210;Integrated Security=" +
            "True")]
        public string BKUP_CEPT_REGISTRATION20211210ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20211210ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=FW5;Initial Catalog=CEPT_Registration;Persist Security Info=True;User" +
            " ID=sa;Password=admin@123")]
        public string CEPT_RegistrationConnectionString3 {
            get {
                return ((string)(this["CEPT_RegistrationConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-VEKFGPV;Initial Catalog=CEPT_Registration;Integrated Security" +
            "=True")]
        public string CEPT_RegistrationConnectionString4 {
            get {
                return ((string)(this["CEPT_RegistrationConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20220214;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20220214ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20220214ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WINDOWS-F7OO0IO\\SQLEXPRESS;Initial Catalog=CEPT_Registration_14022022" +
            ";Integrated Security=True")]
        public string CEPT_Registration_14022022ConnectionString {
            get {
                return ((string)(this["CEPT_Registration_14022022ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=CEPT_Registration_14022022;Integrated" +
            " Security=True")]
        public string CEPT_Registration_14022022ConnectionString1 {
            get {
                return ((string)(this["CEPT_Registration_14022022ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20220321;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20220321ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20220321ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=BKUP_CEPT_REGISTRATION20220426;Integrated Security=" +
            "True")]
        public string BKUP_CEPT_REGISTRATION20220426ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20220426ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=CEPT_REG_02062022;Integrated Security" +
            "=True")]
        public string CEPT_REG_02062022ConnectionString {
            get {
                return ((string)(this["CEPT_REG_02062022ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=CEPT_Registration;Integrated Security=True")]
        public string CEPT_RegistrationConnectionString5 {
            get {
                return ((string)(this["CEPT_RegistrationConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20220615;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20220615ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20220615ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=BKUP_CEPT_REGISTRATION20220715;Integrated Security=" +
            "True")]
        public string BKUP_CEPT_REGISTRATION20220715ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20220715ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20220930;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20220930ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20220930ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20221004;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20221004ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20221004ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20221122;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20221122ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20221122ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20221208;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20221208ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20221208ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=03012023;Integrated Security=True")]
        public string _03012023ConnectionString {
            get {
                return ((string)(this["_03012023ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20230127;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20230127ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20230127ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20230322;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20230322ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20230322ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20230404;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20230404ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20230404ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20230409;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20230409ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20230409ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20230529;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20230529ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20230529ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20230619;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20230619ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20230619ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20230728;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20230728ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20230728ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20230815;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20230815ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20230815ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20230912;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20230912ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20230912ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20240123;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20240123ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20240123ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-PU5PVRV;Initial Catalog=BKUP_CEPT_REGISTRATION20240206;Integr" +
            "ated Security=True")]
        public string BKUP_CEPT_REGISTRATION20240206ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20240206ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=BKUP_CEPT_REGISTRATION20240306;Integrated Security=" +
            "True")]
        public string BKUP_CEPT_REGISTRATION20240306ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20240306ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=BKUP_CEPT_REGISTRATION20240319;Integrated Security=" +
            "True")]
        public string BKUP_CEPT_REGISTRATION20240319ConnectionString {
            get {
                return ((string)(this["BKUP_CEPT_REGISTRATION20240319ConnectionString"]));
            }
        }
    }
}
